version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: prisma-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: prisma_db
      MYSQL_USER: TRIDIP
      MYSQL_PASSWORD: prisma_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=caching_sha2_password

volumes:
  mysql_data: